export { default as Home } from './home';
export { default as About } from './about';
export { default as Contact } from './contact';
export { default as Privacy } from './privacy';
export { default as Teams } from './teams';
export { default as Blogs } from './blogs';
export { default as Blog } from './blog';
export { default as Events } from './events';
export { default as Event } from './event';